version: "3.9"

services:
  # Infrastructure Services
  # API Gateway
  api-gateway:
    build: ./api-gateway
    container_name: apigateway
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - AUTH_SERVICE_URL=http://auth:5001
      - USER_SERVICE_URL=http://user:5002
      - TWEET_SERVICE_URL=http://tweet:5003
      - LIKE_SERVICE_URL=http://like:5006
    depends_on:
      - auth
      - user
      - tweet
      - like
    networks:
      - twitter-network
    restart: unless-stopped

  # Authentication Service
  auth:
    build: ./services/auth
    container_name: auth
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
      - PORT=5001
      - MONGODB_URI=${MONGODB_URI:-mongodb://admin:admin@mongo:27017/auth?authSource=admin}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret}
    networks:
      - twitter-network
    restart: unless-stopped

  # User Service
  user:
    build: ./services/user
    container_name: user
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=development
      - PORT=5002
      - MONGODB_URI=${MONGODB_URI:-mongodb://admin:admin@mongo:27017/user?authSource=admin}
      - AUTH_SERVICE_URL=http://auth:5001
      - TWEET_SERVICE_URL=http://tweet:5003
    depends_on:
      auth:
        condition: service_started
    networks:
      - twitter-network
    restart: unless-stopped

  # Tweet Service
  tweet:
    build: ./services/tweet
    container_name: tweet
    ports:
      - "5003:5003"
    environment:
      - NODE_ENV=development
      - PORT=5003
      - MONGODB_URI=${MONGODB_URI:-mongodb://admin:admin@mongo:27017/tweet?authSource=admin}
      - AUTH_SERVICE_URL=http://auth:5001
      - USER_SERVICE_URL=http://user:5002
    depends_on:
      auth:
        condition: service_started
    networks:
      - twitter-network
    restart: unless-stopped

  # Like Service
  like:
    build: ./services/like
    container_name: like
    ports:
      - "5006:5006"
    environment:
      - NODE_ENV=development
      - PORT=5006
      - MONGODB_URI=${MONGODB_URI:-mongodb://admin:admin@mongo:27017/like?authSource=admin}
      - AUTH_SERVICE_URL=http://auth:5001
      - USER_SERVICE_URL=http://user:5002
      - TWEET_SERVICE_URL=http://tweet:5003
    depends_on:
      auth:
        condition: service_started
    networks:
      - twitter-network
    restart: unless-stopped


volumes:

networks:
  twitter-network:
    driver: bridge
