name: Docker Image CI for GHCR

on:
 push:
  path: 
   - "services/auth/**"

jobs:
 build_and_publish:
  runs-on: ubuntu-latest

  steps:
   - uses: actions/checkout@v4  
   - name: Build and push to GHCR
     run: |
      docker login --username abdulmoiz-bit --password ${{ secrets.GH_PAT }} ghcr.io
      docker build ./services/auth --tag ghcr.io/abdulmoiz-bit/twitterauth:latest
      docker push ghcr.io/abdulmoiz-bit/twitterauth:latest
   
