name: Docker Image CI for GHCR

on:
 push:
  path: 
   - "services/users/**"

jobs:
 build_and_publish:
  runs-on: ubuntu-latest

  steps:
   - uses: actions/checkout@v4  
   - name: Build and push to Docker Hub
     run: |
       docker login --username moizrashid --password ${{ secrets.DOCKER_HUB_TOKEN }}
       docker build ./services/users --tag moizrashid/twitteruser:latest
       docker push moizrashid/twitteruser:latest
   
